services:
  sndb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./bd:/data/db
